source 'http://rubygems.org'

# gem 'activerecord', '<=5.1', :require => 'active_record'
# gem 'sinatra-activerecord'
gem 'bcrypt'
gem 'rack_session_access'


# group :development do
# gem 'sqlite3', '~>1.3.6'
#   # gem 'rspec'
#   gem 'tux'
# end


gem 'sinatra-flash'
gem 'activerecord', '5.2.4.5', :require => 'active_record'
gem 'database_cleaner'
gem 'pry'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3', '~>1.3.6'
gem 'thin'
gem 'tux'
gem 'capybara'
